# Generated by Django 3.2.7 on 2022-04-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_chapter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='poster',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
