# Generated by Django 3.2.7 on 2022-04-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_manga_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='poster',
            field=models.URLField(blank=True, max_length=750),
        ),
    ]
