# Generated by Django 3.2.7 on 2022-04-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_manga_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="manga",
            name="anilist_id",
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="manga",
            name="mal_id",
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
