# Generated by Django 3.2.7 on 2022-04-10 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_manga_volume_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Volume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volume_number", models.IntegerField(default=1)),
                (
                    "manga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.manga"
                    ),
                ),
            ],
            options={
                "unique_together": {("volume_number", "manga")},
            },
        ),
        migrations.AddField(
            model_name="chapter",
            name="volume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.volume",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chapter",
            unique_together={("volume", "chapter_number", "manga")},
        ),
        migrations.RemoveField(
            model_name="chapter",
            name="volume_number",
        ),
    ]
