# Generated by Django 3.2.7 on 2022-04-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220410_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='banner',
            field=models.URLField(blank=True, max_length=750),
        ),
    ]
