# Generated by Django 3.2.7 on 2022-04-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_manga_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="manga",
            name="magazine",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
