# Generated by Django 3.2.7 on 2022-04-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_manga_magazine"),
    ]

    operations = [
        migrations.AddField(
            model_name="manga",
            name="fandom",
            field=models.URLField(blank=True, null=True),
        ),
    ]
