# Generated by Django 3.2.7 on 2022-04-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_volume"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Chapter",
        ),
    ]
