# Generated by Django 3.2.7 on 2022-04-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volume',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
