# Generated by Django 3.2.7 on 2022-04-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_auto_20220415_1353"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="volume",
            unique_together={("absolute_number", "manga")},
        ),
    ]
