# Generated by Django 3.2.7 on 2022-04-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_volume_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="volume",
            name="poster",
            field=models.URLField(blank=True, max_length=750),
        ),
    ]
