# Generated by Django 3.2.7 on 2022-07-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_volume_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="manga",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
