# Generated by Django 4.1.4 on 2022-12-10 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_manga_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volume",
            name="absolute_number",
            field=models.IntegerField(
                default=-1, validators=[django.core.validators.MinValueValidator(-1)]
            ),
        ),
    ]
