# Generated by Django 4.1.4 on 2022-12-11 13:44

from django.db import migrations


def generate_editions_for_volumes(apps, schema_editor):
    Manga = apps.get_model("api", "Manga")
    Edition = apps.get_model("api", "Edition")
    Volume = apps.get_model("api", "Volume")

    for manga in Manga.objects.all():
        # Check if the manga has a standard edition
        e = Edition.objects.filter(manga=manga, name="standard").exists()
        if not e:
            # Make the edition
            edition = Edition.objects.create(name="standard", manga=manga)
            # For all volumes in that manga where there is no edition
            for volume in Volume.objects.filter(edition__isnull=True, manga=manga):
                volume.edition = edition
                volume.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_historicaledition_edition_historicalvolume_edition_and_more"),
    ]

    operations = [
        migrations.RunPython(generate_editions_for_volumes)
    ]
