# Generated by Django 4.1.4 on 2022-12-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_add_editions_to_volumes"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="volume",
            unique_together={("absolute_number", "manga", "edition")},
        ),
    ]
