# Generated by Django 4.1.4 on 2022-12-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_alter_volume_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="edition",
            unique_together={("name", "manga")},
        ),
    ]
