# Generated by Django 4.1.4 on 2022-12-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_alter_volume_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalmanga",
            old_name="banner",
            new_name="banner_url",
        ),
        migrations.RenameField(
            model_name="historicalmanga",
            old_name="poster",
            new_name="poster_url",
        ),
        migrations.RenameField(
            model_name="historicalvolume",
            old_name="poster",
            new_name="poster_url",
        ),
        migrations.RenameField(
            model_name="manga",
            old_name="banner",
            new_name="banner_url",
        ),
        migrations.RenameField(
            model_name="manga",
            old_name="poster",
            new_name="poster_url",
        ),
        migrations.RenameField(
            model_name="volume",
            old_name="poster",
            new_name="poster_url",
        ),
        migrations.AddField(
            model_name="historicalmanga",
            name="banner_file",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalmanga",
            name="poster_file",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalvolume",
            name="poster_file",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="manga",
            name="banner_file",
            field=models.ImageField(blank=True, null=True, upload_to="banners"),
        ),
        migrations.AddField(
            model_name="manga",
            name="poster_file",
            field=models.ImageField(blank=True, null=True, upload_to="posters"),
        ),
        migrations.AddField(
            model_name="volume",
            name="poster_file",
            field=models.ImageField(blank=True, null=True, upload_to="posters"),
        ),
    ]
