# Generated by Django 4.1.4 on 2022-12-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_rename_banner_historicalmanga_banner_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manga",
            name="banner_file",
            field=models.ImageField(blank=True, null=True, upload_to="heroes"),
        ),
    ]
