# Generated by Django 4.1.4 on 2022-12-30 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_genre_historicalmanga_tags_manga_tags_manga_genres"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmanga",
            name="volume_count",
        ),
        migrations.RemoveField(
            model_name="manga",
            name="volume_count",
        ),
    ]
