# Generated by Django 4.1.7 on 2023-02-24 19:47

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalvolume",
            name="isbn",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[api.validators.isbn_validator],
            ),
        ),
        migrations.AddField(
            model_name="historicalvolume",
            name="page_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalvolume",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="volume",
            name="isbn",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[api.validators.isbn_validator],
            ),
        ),
        migrations.AddField(
            model_name="volume",
            name="page_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="volume",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
