# Generated by Django 4.1.7 on 2023-03-12 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_alter_historicalmanga_banner_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmanga",
            name="banner_url",
            field=models.URLField(
                blank=True,
                max_length=750,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The image must be from one of the trusted sites. Learn more about this on the contribution guidelines.",
                        regex="^https?:\\/\\/(s4\\.anilist\\.co|images-na\\.ssl-images-amazon\\.com|static\\.wikia\\.nocookie\\.net\\/.*\\/images|m\\.media-amazon\\.com\\/images|cdn\\.myanimelist\\.net\\/images|uploads\\.mangadex\\.org\\/covers|i\\.gr-assets\\.com\\/images|comicvine\\.gamespot\\.com\\/a\\/uploads|dw9to29mmj727\\.cloudfront\\.net)\\/",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalmanga",
            name="poster_url",
            field=models.URLField(
                blank=True,
                max_length=750,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The image must be from one of the trusted sites. Learn more about this on the contribution guidelines.",
                        regex="^https?:\\/\\/(s4\\.anilist\\.co|images-na\\.ssl-images-amazon\\.com|static\\.wikia\\.nocookie\\.net\\/.*\\/images|m\\.media-amazon\\.com\\/images|cdn\\.myanimelist\\.net\\/images|uploads\\.mangadex\\.org\\/covers|i\\.gr-assets\\.com\\/images|comicvine\\.gamespot\\.com\\/a\\/uploads|dw9to29mmj727\\.cloudfront\\.net)\\/",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalvolume",
            name="poster_url",
            field=models.URLField(
                blank=True,
                max_length=750,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The image must be from one of the trusted sites. Learn more about this on the contribution guidelines.",
                        regex="^https?:\\/\\/(s4\\.anilist\\.co|images-na\\.ssl-images-amazon\\.com|static\\.wikia\\.nocookie\\.net\\/.*\\/images|m\\.media-amazon\\.com\\/images|cdn\\.myanimelist\\.net\\/images|uploads\\.mangadex\\.org\\/covers|i\\.gr-assets\\.com\\/images|comicvine\\.gamespot\\.com\\/a\\/uploads|dw9to29mmj727\\.cloudfront\\.net)\\/",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="manga",
            name="banner_url",
            field=models.URLField(
                blank=True,
                max_length=750,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The image must be from one of the trusted sites. Learn more about this on the contribution guidelines.",
                        regex="^https?:\\/\\/(s4\\.anilist\\.co|images-na\\.ssl-images-amazon\\.com|static\\.wikia\\.nocookie\\.net\\/.*\\/images|m\\.media-amazon\\.com\\/images|cdn\\.myanimelist\\.net\\/images|uploads\\.mangadex\\.org\\/covers|i\\.gr-assets\\.com\\/images|comicvine\\.gamespot\\.com\\/a\\/uploads|dw9to29mmj727\\.cloudfront\\.net)\\/",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="manga",
            name="poster_url",
            field=models.URLField(
                blank=True,
                max_length=750,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The image must be from one of the trusted sites. Learn more about this on the contribution guidelines.",
                        regex="^https?:\\/\\/(s4\\.anilist\\.co|images-na\\.ssl-images-amazon\\.com|static\\.wikia\\.nocookie\\.net\\/.*\\/images|m\\.media-amazon\\.com\\/images|cdn\\.myanimelist\\.net\\/images|uploads\\.mangadex\\.org\\/covers|i\\.gr-assets\\.com\\/images|comicvine\\.gamespot\\.com\\/a\\/uploads|dw9to29mmj727\\.cloudfront\\.net)\\/",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="poster_url",
            field=models.URLField(
                blank=True,
                max_length=750,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The image must be from one of the trusted sites. Learn more about this on the contribution guidelines.",
                        regex="^https?:\\/\\/(s4\\.anilist\\.co|images-na\\.ssl-images-amazon\\.com|static\\.wikia\\.nocookie\\.net\\/.*\\/images|m\\.media-amazon\\.com\\/images|cdn\\.myanimelist\\.net\\/images|uploads\\.mangadex\\.org\\/covers|i\\.gr-assets\\.com\\/images|comicvine\\.gamespot\\.com\\/a\\/uploads|dw9to29mmj727\\.cloudfront\\.net)\\/",
                    )
                ],
            ),
        ),
    ]
