# Generated by Django 4.1.7 on 2023-04-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_alter_historicalvolume_isbn_alter_volume_isbn"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmanga",
            name="is_oneshot",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="manga",
            name="is_oneshot",
            field=models.BooleanField(default=False),
        ),
    ]
