version: 2.1
jobs:
  test-and-lint:
    docker:
      - image: cimg/python:3.10.1-node
      - image: cimg/postgres:14.1
    environment:
      DATABASE_URL: postgresql://postgres:@localhost/test_tankobon
      DEBUG: True
      SECRET_KEY: test
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_STORAGE_BUCKET_NAME: test
      AWS_S3_REGION_NAME: test
    steps:
      - checkout
      - run:
          name: Check node version
          command: node --version
      - run:
          name: Install pipenv
          command: pip install pipenv
      - run:
          name: Install pylint
          command: pip install pylint
      - run:
          name: Install dependencies
          command: pipenv install --system --dev
      - run:
          name: Lint
          command: pylint $(git ls-files '*.py')
      - run:
          name: Install Tailwind deps
          command: cd tankobon/theme/static_src && npm install
      - run:
          name: Compile assets
          command: python manage.py tailwind build && python manage.py collectstatic --noinput
      - run:
          name: Run tests
          command: python manage.py test
  deploy:
    docker:
        - image: alpine:3.12
    steps:
        - checkout
        - run: 
            name: Deploy to Fly
            command: |
                chmod +x deploy.sh
                ./deploy.sh

workflows:
  build-and-test-workflow:
    jobs:
      - test-and-lint
      - deploy:
          requires:
              - test-and-lint
          filters:
              branches:
                  only: master
